config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :admin do
    resources :active_sale_events do
      collection do
        get :products
        post :update_positions
      end
      member do
        put :update_events
      end
      resources :sale_images do
        collection do
          post :update_positions
        end
      end
    end
  end
end

app/models/spree/active_sale_event.rb
# EVENTS
# Events represent an entity for active sale in a flash sale/ daily deal.
# There can be many events for one sale, just like taxonomies in spree.
#
module Spree
  class ActiveSaleEvent < Spree::SaleEvent

    before_validation :update_permalink
    before_save :have_valid_position

    #TODO has_many :sale_images, :as => :viewable, :dependent => :destroy, :order => 'position ASC'
    belongs_to :product
    belongs_to :active_sale

#    attr_accessible :description, :end_date, :eventable_id, :eventable_type, :is_active, :is_hidden, :is_permanent, :name, :permalink, :active_sale_id, :start_date, :eventable_name, :discount, :parent_id

    validates :name, :permalink, :start_datetime, :end_datetime, :presence => true

    # Spree::ActiveSaleEvent.is_live? method
    # should only/ always represents live and active events and not just live events.
    def is_live? object
      object_class_name = object.class.name
      return object.live_and_active? if object_class_name == self.name
      %w(Spree::Product Spree::Variant Spree::Taxon).include?(object_class_name) ? object.live? : false
    end

    def product_name
      product.try(:name)
    end

    def product_name=(name)
      self.product = Product.find_by_name(name) if name.present?
    end

    def update_permalink
      prefix = {"Spree::Taxon" => "t", "Spree::Product" => "products"}
      self.permalink = self.product.friendly_id unless self.product.nil?
    end

    # This callback basically makes sure that parents for an event lives longer.
    # Or at least parents live for the time when event is live.
    def update_parent_active_sales
      active_sale_events = self.self_and_ancestors
      parents = self.ancestors
      oldest_start_datetime = active_sale_events.not_blank_and_sorted_by(:start_datetime).first
      latest_end_datetime = active_sale_events.not_blank_and_sorted_by(:end_datetime).last
      parents.each{ |parent| 
        parent.update_attributes(:start_datetime => oldest_start_datetime) if parent.start_datetime.nil? ? true : (parent.start_datetime > oldest_start_datetime) 
        parent.update_attributes(:end_datetime => latest_end_datetime) if parent.end_datetime.nil? ? true : (parent.end_datetime < latest_end_datetime)
      }
    end
  end
end

app/controllers/spree/admin/active_sale_events_controller.rb
module Spree
  module Admin

    class ActiveSaleEventsController < ResourceController
      respond_to :json, :only => [:update_events]

      def index
        respond_with(@collection) do |format|
          format.html
          format.json { render :json => json_data }
        end
      end

      def show
        redirect_to( :action => :edit )
      end

      def destroy
        @active_sale_event = Spree::ActiveSaleEvent.find(params[:id])
        @active_sale_event.destroy
        respond_with(@active_sale_event) { |format| format.json { render :json => '' } }
      end

      def products
        search = Product.search(:name_cont => params[:name])
        render :json => search.result.map(&:name)
      end

      def update_events
        @active_sale_event.update_attributes(params[:active_sale_event])
        respond_with(@active_sale_event)
      end

      protected

        def collection
          return @collection if @collection.present?
          @search = Spree::ActiveSaleEvent.where(:active_sale_id => params[:active_sale_id]).ransack(params[:q])
          @collection = @search.result.page(params[:page]).per(Spree::ActiveSaleConfig[:admin_active_sale_events_per_page])
        end

        def permitted_active_sale_attributes
          [
            :name, :description, :permalink, :start_datetime, :end_datetime,
            :is_active, :is_hidden, :is_permanent, :discount_percentage, :product_id
          ]
        end

        def product_hash
          if product_name = params[:active_sale].delete(:product_name)
            product = Product.find_by_name(product_name)
            { product_id: product.id, permalink: product.friendly_id }
          else
            {}
          end
        end



    end
  end
end

app/helpers/spree/active_sale_events_helper.rb
module Spree
  module ActiveSaleEventsHelper
    
    def sale_event_timer(event = nil, layout = nil)
      return I18n.t('spree.active_sale.event.can_not_be_nil') if (event == nil) || (event.class.name != "Spree::ActiveSaleEvent")
      layout ||= '{dn} DAYS {hnn}{sep}{mnn}{sep}{snn}'
      content_tag(:span, I18n.t('spree.active_sale.event.ending_message'), :class => 'sale_event_message') + " " + content_tag(:span, event.end_date.strftime('%Y-%m-%dT%H:%M:%S'), "data-timer" => event.end_date.strftime('%Y-%m-%dT%H:%M:%S'), "data-layout" => layout, :class => 'sale_event_message_timer')
    end

    def sale_image_available?(sale_event)
      !sale_event.sale_images.empty? || sale_event.eventable_image_available?
    end

    private

    def define_sale_image_method(style)
      self.class.send :define_method, "#{style}_event_image" do |sale_event, *options|
        options = options.first || {}
        if sale_event.sale_images.empty?
          image_tag "noimage/#{style}.png", options
        else
          image = sale_event.sale_images.first
          options.reverse_merge! :alt => image.alt.blank? ? sale_event.name : image.alt
          image_tag image.attachment.url(style), options
        end
      end
    end

    def event_js_data(event)
      return nil if event.blank?
      Spree::ActiveSaleConfig[:name_with_event_position?] ? "#{event.name.gsub('"','\"')} - #{I18n.t('spree.active_sale.event.active_record.position')}: #{event.position}" : event.name.gsub('"','\"')
    end
  end
end

app/views/spree/admin/active_sale_events/_form.html.erb
<% if @active_sale_event.try(:errors).present? %>
  <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @active_sale_event } %>
<% end %>

  <fieldset data-hook="admin_active_sale_event_form_fields">

    <div class="clearfix">
      <div class="left eight columns alpha" data-hook="admin_active_sale_event_form_left">
        <%= form.field_container :name do %>
          <%= form.label :name, raw(t('spree.active_sale.event.active_record.name') + content_tag(:span, ' *', :class => 'required')) %>
          <%= form.text_field :name, :class => 'fullwidth' %>
          <%= form.error_message_on :name %>
        <% end %>
        <%= form.field_container :description do %>
          <%= form.label :description, t('spree.active_sale.event.active_record.description') %>
          <%= form.text_area :description, {:cols => 60, :rows => 10, :class => 'fullwidth'} %>
          <%= form.error_message_on :description %>
        <% end %>
      </div>

      <div class="right eight columns omega" data-hook="admin_active_sale_event_form_right">
        <div class="row">
          <div class="alpha four columns">
            <%= form.field_container :start_datetime do %>
              <%= form.label :start_datetime, t('spree.active_sale.event.active_record.start_datetime') %>
              <%= form.error_message_on :start_datetime %>
              <% if @active_sale_event.start_datetime? %>
                <% start_datetime = l(@active_sale_event.start_datetime, :format => t('spree.active_sale.event.datetimepicker.format')) %>
              <% else %>
                <% start_datetime = l(Time.zone.now, :format => t('spree.active_sale.event.datetimepicker.format')) %>
              <% end %>
              <%= form.text_field :start_datetime, :value => start_datetime, :class => 'timepicker' %>
            <% end %>
          </div>
  
          <div class="omega four columns">
            <%= form.field_container :end_datetime do %>
              <%= form.label :end_datetime, t('spree.active_sale.event.active_record.end_datetime') %>
              <%= form.error_message_on :end_datetime %>
              <% end_datetime = l((@active_sale_event.end_datetime? ? @active_sale_event.end_datetime : Time.zone.now+1.day), :format => t('spree.active_sale.event.datetimepicker.format')) %>
              <%= form.text_field :end_datetime, :value => end_datetime, :class => 'timepicker' %>
            <% end %>
          </div>
        </div>
        <div class="row">
          <div class="omega four columns">
            <%= form.label :product_name, t('spree.active_sale.event.active_record.product_name', :default => :product_name) %>
            <p class='hint'><%= t('spree.active_sale.event.product_name_hint') %></p>
            <%= form.error_message_on :product_name %>
            <%= form.text_field :product_name, :class => 'autocomplete', :data => { :auto_complete_url => products_admin_active_sale_events_url } %>
          </div>
        </div>
        <div class="row">
          <div class="alpha four columns clearfix">
            <%= form.field_container :is_active, :class => ['checkbox'] do %>
              <label>
                <%= form.check_box :is_active %>
                <%= t('spree.active_sale.event.active_record.is_active') %>
                <%= form.error_message_on :is_active %>
              </label>
            <% end %>
  
            <%= form.field_container :is_hidden, :class => ['checkbox'] do %>
              <label>
                <%= form.check_box :is_hidden %>
                <%= t('spree.active_sale.event.active_record.is_hidden') %>
                <%= form.error_message_on :is_hidden %>
              </label>
            <% end %>
  
            <%= form.field_container :is_permanent, :class => ['checkbox'] do %>
              <label>
                <%= form.check_box :is_permanent %>
                <%= t('spree.active_sale.event.active_record.is_permanent') %>
                <%= form.error_message_on :is_permanent %>
              </label>
            <% end %>
          </div>
  
          <div class="omega four columns">
          <%= form.field_container :discount_percentage do %>
            <%= form.label :discount_percentage, t('spree.active_sale.event.active_record.discount_percentage', :default => :discount_percentage) %>
            <p class='hint'><%= t('spree.active_sale.event.discount_percentage_hint') %></p>
            <%= form.error_message_on :discount_percentage %>
            <%= form.text_field :discount_percentage %>
          <% end %>
          </div>
        </div>

      </div>
    </div>

    <p class="form-buttons" data-hook="admin_active_sale_form_buttons">
      <% if @active_sale_event.new_record? %>
        <%= render :partial => 'spree/admin/shared/new_resource_links' %>
      <% else %>
        <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
      <% end %>
    </p>
  </fieldset>

<%= javascript_tag do -%>
  var properties = "<%= raw(@properties.to_json) %>";

  $("#admin_active_sale_event input.autocomplete").on("keydown", function(){
    var product_name = $('#active_sale_event_product_name').val();
    var url = $(this).data('auto-complete-url')
    already_auto_completed = $(this).is('ac_input');
    if (!already_auto_completed) {
      $(this).autocomplete({
        source: url+"?name="+product_name
      });
      $(this).focus();
    }
  });
<% end -%>

app/views/spree/admin/active_sale_events/edit.html.erb
<% content_for :page_title do %>
  <%= @active_sale_event.name %> &#62; <%= @active_sale_event.start_datetime.to_date %> &#62; <%= t('spree.active_sale.event.title.edit') %>
<% end %>

<div data-hook="admin_active_sale_event_edit_form">
  <div id="active-sale-event-form-wrapper">
    <%= form_for [:admin, @active_sale_event], :html => { :id => 'admin_active_sale_event', :multipart => true } do |form| %>
      <%= render :partial => 'form', :locals => { :form => form } %>
    <% end %>
  </div>
</div>

app/views/spree/admin/active_sale_events/index.html.erb
<% content_for :page_title do %>
  <%= t('spree.active_sale.title.list') %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to t('spree.active_sale.link.new'), new_object_url, :icon => 'icon-plus', :id => 'admin_new_active_sale_link' %>
  </li>
<% end %>

<div id="new_active_sale" data-hook></div>

<table class="index sortable" id='listing_active_sales' data-hook data-sortable-link="<%= update_positions_admin_active_sale_events_url %>">
  <colgroup>
    <col style="width: 85%">
    <col style="width: 15%">
  </colgroup>
  <thead>
    <tr data-hook="active_sales_header">
      <th><%= t('spree.active_sale.active_record.name') %></th>
      <th class="actions"></th>
    </tr>
  </thead>
  <tbody>

    <% @collection.each do |active_sale_event| %>
      <tr id="<%= spree_dom_id active_sale_event %>" data-hook="active_sales_row" class="<%= cycle('odd', 'even')%>">
        <td>
          <span class="handle"></span>&nbsp;
          <%= link_to active_sale_event.name, object_url(active_sale_event) %>
        </td>
        <td class="actions">
          <%= link_to_edit active_sale_event, :no_text => true %>
          <%= link_to_delete active_sale_event, :no_text => true %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%#= paginate @active_sales %>

<% content_for :sidebar_title do %>
  <%= Spree.t(:search) %>
<% end %>

<% content_for :sidebar do %>
  <div class="box align-center" data-hook="admin_active_sales_index_search">    
    <%= search_form_for [:admin, @search] do |f| %>
      <div class="field">
        <%= f.label Spree.t(:name) %> <br>
        <%= f.text_field :name_cont, :class => 'fullwidth' %>
      </div>
      <div data-hook="admin_active_sales_index_search_buttons">
        <%= button Spree.t(:search), 'icon-search' %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/spree/admin/active_sale_events/new.html.erb
<% content_for :page_title do %>
  <%= @active_sale_event.name %> &#62; <%= t('spree.active_sale.event.title.new') %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to t('spree.active_sale.event.link.back'), [:admin, @active_sale, @active_sale_event], :icon => 'icon-arrow-left', :id => 'admin_new_active_sale_event_link' %>
  </li>
<% end %>

<div data-hook="admin_active_sale_event_edit_form">
  <div id="active-sale-event-form-wrapper">
    <%= form_for [:admin, @active_sale, @active_sale_event], :html => { :id => 'admin_active_sale_event', :multipart => true } do |form| %>
      <%= render :partial => 'form', :locals => { :form => form } %>
    <% end %>
  </div>
</div>